<a href="https://colab.research.google.com/github/wajihabibi/RhombixTechnologies_Tasks/blob/main/DATA_PREPROCESSING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK 2**

In [100]:
# IMPORT LIBRARIES

In [157]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [158]:
# LOAD DATASET

In [159]:
df = pd.read_csv("student_performance_dataset.csv")

In [160]:
# CHECK FIRST 5 ROWS

In [161]:
df.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

In [162]:
# NOW CHECK SHAPE

In [163]:
df.shape

(1000, 12)

In [164]:
#  DATATYPES AND MISSING VALUES

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [166]:
# CHECK MISSING VALUES

In [167]:
df.isnull().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

### we have 102 missing values in (parental_education) column, this is categorical coumn so fill with mode.

In [170]:
# FILL MISSING VALUES

In [171]:
df["parental_education"] = df["parental_education"].fillna(df["parental_education"]).mode()[0]

In [172]:
# AFTER FILLING CHECK MISSING VALUES

In [173]:
df.isnull().sum()

student_id                    0
gender                        0
study_time_hours              0
attendance_percent            0
sleep_hours                   0
parental_education            0
internet_access               0
extracurricular_activities    0
part_time_job                 0
previous_grade                0
final_exam_score              0
final_grade                   0
dtype: int64

In [174]:
# CHECK DUPLICATES

In [175]:
df.duplicated().sum()

np.int64(0)

In [176]:
# CHECK STATISTICAL SUMMARY OF NUMERICAL COLUMNS

In [177]:
df.describe()

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.570700,85.092300,6.799500,69.740900,83.543500
std,288.819436,1.478559,9.270685,1.203527,12.613425,10.341333
min,1.000000,0.500000,54.800000,3.200000,31.300000,46.800000
25%,250.750000,2.600000,78.800000,5.900000,61.000000,76.075000
50%,500.500000,3.600000,85.200000,6.800000,69.600000,83.800000
75%,750.250000,4.500000,91.900000,7.600000,78.400000,91.525000
max,1000.000000,8.100000,100.000000,10.000000,100.000000,100.000000

In [178]:
# SEE OUTLIERS THROUGH IQR

In [179]:
numerical_cols = ['study_time_hours','attendance_percent','sleep_hours','previous_grade', 'final_exam_score']

In [180]:
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print(f"\n{col}")

    print("Q1:", Q1)

    print("Q3:", Q3)

    print("IQR:", IQR)
    print("Lower bound:", lower_bound)
    print("Upper bound:", upper_bound)

study_time_hours
Q1: 2.6
Q3: 4.5
IQR: 1.9
Lower bound: -0.24999999999999956
Upper bound: 7.35

attendance_percent
Q1: 78.8
Q3: 91.9
IQR: 13.100000000000009
Lower bound: 59.149999999999984
Upper bound: 111.55000000000001

sleep_hours
Q1: 5.9
Q3: 7.6
IQR: 1.6999999999999993
Lower bound: 3.3500000000000014
Upper bound: 10.149999999999999

previous_grade
Q1: 61.0
Q3: 78.4
IQR: 17.400000000000006
Lower bound: 34.89999999999999
Upper bound: 104.50000000000001

final_exam_score
Q1: 76.07499999999999
Q3: 91.525
IQR: 15.450000000000017
Lower bound: 52.89999999999996
Upper bound: 114.70000000000003

In [181]:
# CHECK ACTUAL OUTLIER VALUES

In [182]:
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ][col]

    print(f"\n{col}")
    print("Number of outliers:", len(outliers))
    print("Outlier values:", outliers.tolist())

study_time_hours
Number of outliers: 4
Outlier values: [8.1, 7.4, 7.4, 7.4]

attendance_percent
Number of outliers: 6
Outlier values: [56.3, 55.8, 58.0, 55.6, 54.8, 59.0]

sleep_hours
Number of outliers: 2
Outlier values: [3.2, 3.3]

previous_grade
Number of outliers: 3
Outlier values: [31.3, 34.5, 33.5]

final_exam_score
Number of outliers: 1
Outlier values: [46.8]

In [183]:
# HANDLED OUTLIERS

In [184]:
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[col] = df[col].clip(
        lower=lower_bound,
        upper=upper_bound
    )

In [185]:
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ][col]

    print(f"\n{col}")
    print("Number of outliers:", len(outliers))

study_time_hours
Number of outliers: 0

attendance_percent
Number of outliers: 0

sleep_hours
Number of outliers: 0

previous_grade
Number of outliers: 0

final_exam_score
Number of outliers: 0

In [186]:
# SEPARATE FEATURES AND TARGET

## OUR TARGET IS FINAL GRADE

In [187]:
X = df.drop(columns=['student_id', 'final_grade'])
y = df['final_grade']

In [188]:
# CHECK SHAPES

In [189]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1000, 10)
y shape: (1000,)

In [190]:
# SPLIT THE DATA INTO TRAINING AND TESTING

In [191]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=42)

In [192]:
# CHECK SIZES

In [193]:
print("X_train:", X_train.shape)

print("X_test:",X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (800, 10)
X_test: (200, 10)
y_train: (800,)
y_test: (200,)

In [198]:
# SEPARATE CATEGORICAL AND NUMERICAL

In [202]:
numerical_features = ["study_time_hours","attendance_percent","sleep_hours","previous_grade","final_exam_score"]

categorical_features = ["gender","parental_education","internet_access","extracurricular_activities","part_time_job"]

In [203]:
# PREPROCESSING TRANSFORMER

In [204]:
preprocessor = ColumnTransformer(
transformers=[('num', StandardScaler(), numerical_features),('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features )]
    )

In [205]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [206]:
# CHECK SHAPE

In [207]:
print("Processed X_train shape:", X_train_processed.shape)
print("Processed X_test shape:", X_test_processed.shape)

Processed X_train shape: (800, 14)
Processed X_test shape: (200, 14)

In [208]:
# CHECK MISSING VALUES

In [209]:
print("Missing values in X_train:",np.isnan(X_train_processed).sum())

print("Missing values in X_test:", np.isnan(X_test_processed).sum())

Missing values in X_train: 0
Missing values in X_test: 0

In [210]:
# FINAL CHECK

In [211]:
print("Training data:", X_train_processed.shape)
print("Testing data:", X_test_processed.shape)
print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

Training data: (800, 14)
Testing data: (200, 14)
Training target: (800,)
Testing target: (200,)